"""initial migration

Revision ID: 9bffcd106ef1
Revises:
Create Date: 2026-09-23 17:38:34.033708

"""
from alembic import op
import sqlalchemy as sa
from app.persistence.workflow_run_model import JSONBType


# revision identifiers, used by Alembic.
revision = '9bffcd106ef1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('requirement', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('workflow_state', JSONBType(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workflow_runs')
    # ### end Alembic commands ###